title: Prometheus MSLA Documentation
description: Documentation for the Prometheus MSLA
theme: just-the-docs
url: https://stefanraatz.github.io/Justthedocstemplate
color_scheme: dark
aux_links:
  Prometheus Dokumentation: https://github.com/StefanRaatz/JustTheDocsTemplate
  Prometheus Project Page: https://github.com/TheContrappostoShop/Prometheus-MSLA
  The Contrapposto Shop: https://github.com/TheContrappostoShop
  