title: Prometheus MSLA Dokumentation
description: Dokumentation for the Prometheus MSLA
theme: just-the-docs

url: https://stefanraatz.github.io/Justthedocstemplate

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
